name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build for Linux
        run: |
          poetry run pyinstaller --onefile run.py --distpath dist/linux
          ls -al dist/linux

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hello-world-linux
          path: dist/linux/

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build for Windows
        run: |
          poetry run pyinstaller --onefile run.py --distpath dist/win
          ls -al dist/win

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hello-world-windows
          path: dist/win/

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build for MacOS
        run: |
          poetry run pyinstaller --onefile run.py --distpath dist/mac
          ls -al dist/mac

      - name: Upload MacOS artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hello-world-macos
          path: dist/mac/
